/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.SistemaVendas.apresentacao;

import br.edu.ifnmg.DataAcess.FormasPagamentoDAO;
import br.edu.ifnmg.SistemaVendas.entidade.ErroValidacaoException;
import br.edu.ifnmg.SistemaVendas.entidade.FormadePagamento;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



    // Variables declaration - do not modify                     

    // Variables declaration - do not modify                     

    // Variables declaration - do not modify                     
public class frmCadastroFormaPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCadastroFormaPagamento
     */
    public frmCadastroFormaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFormaPagamento = new javax.swing.JLabel();
        txtFormaPagamento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Forma de Pagamento");

        lbFormaPagamento.setText("Forma de Pagamento: ");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbFormaPagamento)
                        .addGap(20, 20, 20)
                        .addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnSalvar)
                        .addGap(36, 36, 36)
                        .addComponent(btnCancelar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFormaPagamento)
                    .addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       int confirmar = JOptionPane.showConfirmDialog(null, "Deseja Cancelar?","Deseja Cancelar?", JOptionPane.OK_CANCEL_OPTION);
        if (JOptionPane.OK_OPTION == confirmar){
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       int confirmar = JOptionPane.showConfirmDialog(null, "Deseja Salvar?","Deseja Salvar?", JOptionPane.OK_CANCEL_OPTION);
        if (JOptionPane.OK_OPTION == confirmar){
        
            if(txtFormaPagamento.getText().isEmpty() ){
            JOptionPane.showMessageDialog(rootPane, "O campo Forma de Pagamento deve ser preenchido");
        }
            else{
                             
             FormadePagamento aa = new FormadePagamento();
            
                aa.setNome(txtFormaPagamento.getText());
                
            
                         
                try {
                    FormasPagamentoDAO dao = new FormasPagamentoDAO();
                    
                    if(dao.Salvar(aa)){
                                      
                    JOptionPane.showMessageDialog(this,"Dados gravados com sucesso");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Erro ao gravar os dados");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(frmCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                            limpaCampos();
                   
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lbFormaPagamento;
    private javax.swing.JTextField txtFormaPagamento;
    // End of variables declaration//GEN-END:variables

    private void limpaCampos() {
       this.txtFormaPagamento.setText("");
    }
}
